<?php

// MEMULAI SESSION. AGAR DAPAT MENGGUNAKAN, MEMBUAT, ATAU MENGHAUNCURKAN SESSION
session_start();

// IMPORT FILE FUNCTIONS, UNTUK CONNECT KE DATABASE, KARENA
// KONFIGURASI DATABASE TERDAPAT DI FILE TERSEBUT
require '../functions.php';

// JIKA TOMBOL REGISTER DITEKAN, EKSEKUSI PROGRAM BERIKUT
if (isset($_POST['register'])) {

    // JALANKAN FUNGSI REGISTER DI FILE FUNCTIONS,
    // APABILA FUNCTION MENGEMBALIKAN NILAI > 0
    // YANG ARTINYA USER BARU BERHASIL DITAMBAHKAN DI DATABASE
    // EKSEKUSI PROGRAM BERIKUT
    if (registrasi($_POST) > 0) {
        
        // JIKA BERHASIL, BUAT VARIABEL SESSION SEBAGAI BERIKUT
        // GUNANYA UNTUK MELAKUKAN PENGECEKAN DISETIAP HALAMAN
        // SUDAH LOGIN / BELUM
        // KARENA APABILA BERHASIL REGISTER AKAN OTOMATIS LOGIN 
        $_SESSION['login'] = true;
        $_SESSION['username'] = $_POST['username'];
        $_SESSION['loginIsSuccess'] = true;

        // DATA USER BERHASIL DITAMBAHKAN, LEMPAR USER KE HALAMAN DASHBOARD (HALAMAN BERHASIL)
        header('Location: /web-olshop/dashboard.php');

    // JIKA TIDAK BERHASIL MENAMBAHKAN USER BARU, LEMPAR USER KEHALAMAN UTAMA 
    } else {

        $_SESSION["registerError"] = true;
        header('Location: /web-olshop/');

    }

}

?>
